config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  resources :tips

  root 'welcome#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tip.rb
class Tip < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/tips_controller.rb
class TipsController < ApplicationController
  def index
    @tips = Tip.all
  end

  def show
    @tip = Tip.find(params[:id])
  end

  def new
  end

  def edit
  end

  def create
    @tip = Tip.new(tip_params)

    @tip.save
    redirect_to @tip
  end

  def update
  end

  def destroy
  end

  private
  def tip_params
    params.require(:tip).permit(:title, :text)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tips_helper.rb
module TipsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ETP</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tips/index.html.erb
<h1>Listing Tips</h1>

<%= link_to 'Add Tip', new_tip_path %>

<table>
  <tr>
    <th>Title</th>
    <th>Text</th>
  </tr>

  <% @tips.each do |tip| %>
    <tr>
      <td><%= tip.title %></td>
      <td><%= tip.text %></td>
      <td><%= link_to 'Show', tip_path(tip) %></td>
    </tr>
  <% end %>
</table>

app/views/tips/new.html.erb
<h1>New Tip</h1>

<%= form_with scope: :tip, url: tips_path, local: true do |form| %>
  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </p>

  <p>
    <%= form.label :text %><br>
    <%= form.text_area :text %>
  </p>

  <p>
    <%= form.submit %>
  </p>
<% end %>


<%= link_to 'Back', tips_path %>

app/views/tips/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @tip.title %>
</p>

<p>
  <strong>Text:</strong>
  <%= @tip.text %>
</p>


<%= link_to 'Back', tips_path %>

app/views/welcome/index.html.erb
<h1>Engage The Positive</h1>
<%= link_to 'View Tips', controller: 'tips' %>